### ISSUE TITLE
Missing Account.findById

### ISSUE THREAD

**Issue by wtlin1228** [mike-works/web-security-fundamentals#277]
There is no `Account.findById` in the `/server/models/account.js`.
So I can't transfer money between accounts.

Transfer works after I added the following code.

```JavaScript
Account.findById = function (accountId) {
  return Account.findOne({
    where: { id: accountId },
    attributes: ['id', 'userId', 'name', 'number', 'balance']
  }).then(account => {
    if (!account) throw new Error("No account found");
    return account;
  })
}
```

**Comment by wtlin1228** [comment]
Maybe it's caused by upgrading sequelize to 5.21.7 from 5.21.6 in this commit.

https://github.com/mike-works/web-security-fundamentals/commit/d608cbb3a3fb93ad8311f1b1cbad0b15dcda637e

**Comment by RabeaGleissner** [comment]
Thanks for that @wtlin1228 !
I just ran into the same issue and this fixed it 👍

**Comment by BlackFalcons** [comment]
@wtlin1228 and @RabeaGleissner You could probably downgrade but the propper solution is to fix the outdated method which is replacing the `.map(accountId => Account.findById(accountId))` in `server/routes/transfers.js` with `.map(accountId => Account.findByPk(accountId))` where we are replacing the `findById` method with the updated code `findByPk`.

**Comment by dtauer** [comment]
If anyone is still having issues with this, you can replace `findById` with `findByPk`. I also recommend using Node version `8.17.0` with this course.
